// Night Owl Theme
export const nightOwlTheme = {
    base: "vs-dark",
    inherit: true,
    rules: [
        { background: "011627", token: "" },
        { foreground: "637777", token: "comment" },
        { foreground: "c792ea", token: "keyword" },
        { foreground: "c792ea", token: "storage" },
        { foreground: "c792ea", token: "storage.type" },
        { foreground: "ffcb8b", token: "entity.name.class" },
        { foreground: "ffcb8b", token: "entity.name.type.class" },
        { foreground: "addb67", token: "string" },
        { foreground: "addb67", token: "constant.other.symbol" },
        { foreground: "82aaff", token: "entity.name.function" },
        { foreground: "82aaff", token: "meta.function-call" },
        { foreground: "82aaff", token: "support.function" },
        { foreground: "f78c6c", token: "constant.numeric" },
        { foreground: "f78c6c", token: "constant.language" },
        { foreground: "7fdbca", token: "variable" },
        { foreground: "7fdbca", token: "support.variable" },
        { foreground: "ef5350", token: "entity.name.tag" },
        { foreground: "c792ea", token: "entity.other.attribute-name" },
        { foreground: "d6deeb", token: "punctuation" },
    ],
    colors: {
        "editor.foreground": "#d6deeb",
        "editor.background": "#011627",
        "editor.selectionBackground": "#1d3b53",
        "editor.lineHighlightBackground": "#01111d",
        "editorCursor.foreground": "#80a4c2",
        "editorWhitespace.foreground": "#2e3440",
        "editorIndentGuide.background": "#5e81ac",
    },
}

// Dracula Theme
export const draculaTheme = {
    base: "vs-dark",
    inherit: true,
    rules: [
        { background: "282a36", token: "" },
        { foreground: "6272a4", token: "comment" },
        { foreground: "ff79c6", token: "keyword" },
        { foreground: "ff79c6", token: "storage" },
        { foreground: "ff79c6", token: "storage.type" },
        { foreground: "8be9fd", token: "entity.name.class" },
        { foreground: "8be9fd", token: "entity.name.type.class" },
        { foreground: "f1fa8c", token: "string" },
        { foreground: "f1fa8c", token: "constant.other.symbol" },
        { foreground: "50fa7b", token: "entity.name.function" },
        { foreground: "50fa7b", token: "meta.function-call" },
        { foreground: "50fa7b", token: "support.function" },
        { foreground: "bd93f9", token: "constant.numeric" },
        { foreground: "bd93f9", token: "constant.language" },
        { foreground: "f8f8f2", token: "variable" },
        { foreground: "f8f8f2", token: "support.variable" },
        { foreground: "ff79c6", token: "entity.name.tag" },
        { foreground: "50fa7b", token: "entity.other.attribute-name" },
        { foreground: "f8f8f2", token: "punctuation" },
    ],
    colors: {
        "editor.foreground": "#f8f8f2",
        "editor.background": "#282a36",
        "editor.selectionBackground": "#44475a",
        "editor.lineHighlightBackground": "#343746",
        "editorCursor.foreground": "#f8f8f2",
        "editorWhitespace.foreground": "#424450",
        "editorIndentGuide.background": "#424450",
    },
}

// Monokai Theme
export const monokaiTheme = {
    base: "vs-dark",
    inherit: true,
    rules: [
        { background: "272822", token: "" },
        { foreground: "75715e", token: "comment" },
        { foreground: "f92672", token: "keyword" },
        { foreground: "f92672", token: "storage" },
        { foreground: "f92672", token: "storage.type" },
        { foreground: "a6e22e", token: "entity.name.class" },
        { foreground: "a6e22e", token: "entity.name.type.class" },
        { foreground: "e6db74", token: "string" },
        { foreground: "e6db74", token: "constant.other.symbol" },
        { foreground: "a6e22e", token: "entity.name.function" },
        { foreground: "a6e22e", token: "meta.function-call" },
        { foreground: "a6e22e", token: "support.function" },
        { foreground: "ae81ff", token: "constant.numeric" },
        { foreground: "ae81ff", token: "constant.language" },
        { foreground: "fd971f", token: "variable" },
        { foreground: "fd971f", token: "support.variable" },
        { foreground: "f92672", token: "entity.name.tag" },
        { foreground: "a6e22e", token: "entity.other.attribute-name" },
        { foreground: "f8f8f2", token: "punctuation" },
    ],
    colors: {
        "editor.foreground": "#f8f8f2",
        "editor.background": "#272822",
        "editor.selectionBackground": "#49483e",
        "editor.lineHighlightBackground": "#32332d",
        "editorCursor.foreground": "#f8f8f0",
        "editorWhitespace.foreground": "#3b3c35",
        "editorIndentGuide.background": "#3b3c35",
    },
}

// One Dark Theme
export const oneDarkTheme = {
    base: "vs-dark",
    inherit: true,
    rules: [
        { background: "282c34", token: "" },
        { foreground: "5c6370", token: "comment" },
        { foreground: "c678dd", token: "keyword" },
        { foreground: "c678dd", token: "storage" },
        { foreground: "c678dd", token: "storage.type" },
        { foreground: "e5c07b", token: "entity.name.class" },
        { foreground: "e5c07b", token: "entity.name.type.class" },
        { foreground: "98c379", token: "string" },
        { foreground: "98c379", token: "constant.other.symbol" },
        { foreground: "61afef", token: "entity.name.function" },
        { foreground: "61afef", token: "meta.function-call" },
        { foreground: "61afef", token: "support.function" },
        { foreground: "d19a66", token: "constant.numeric" },
        { foreground: "d19a66", token: "constant.language" },
        { foreground: "e06c75", token: "variable" },
        { foreground: "e06c75", token: "support.variable" },
        { foreground: "e06c75", token: "entity.name.tag" },
        { foreground: "d19a66", token: "entity.other.attribute-name" },
        { foreground: "abb2bf", token: "punctuation" },
    ],
    colors: {
        "editor.foreground": "#abb2bf",
        "editor.background": "#282c34",
        "editor.selectionBackground": "#3e4451",
        "editor.lineHighlightBackground": "#21252b",
        "editorCursor.foreground": "#528bff",
        "editorWhitespace.foreground": "#3b4048",
        "editorIndentGuide.background": "#3b4048",
    },
}

// One Darker Theme (darker variant of One Dark)
export const oneDarkerTheme = {
    base: "vs-dark",
    inherit: true,
    rules: [
        { background: "1e2127", token: "" },
        { foreground: "545862", token: "comment" },
        { foreground: "c678dd", token: "keyword" },
        { foreground: "c678dd", token: "storage" },
        { foreground: "c678dd", token: "storage.type" },
        { foreground: "e5c07b", token: "entity.name.class" },
        { foreground: "e5c07b", token: "entity.name.type.class" },
        { foreground: "98c379", token: "string" },
        { foreground: "98c379", token: "constant.other.symbol" },
        { foreground: "61afef", token: "entity.name.function" },
        { foreground: "61afef", token: "meta.function-call" },
        { foreground: "61afef", token: "support.function" },
        { foreground: "d19a66", token: "constant.numeric" },
        { foreground: "d19a66", token: "constant.language" },
        { foreground: "e06c75", token: "variable" },
        { foreground: "e06c75", token: "support.variable" },
        { foreground: "e06c75", token: "entity.name.tag" },
        { foreground: "d19a66", token: "entity.other.attribute-name" },
        { foreground: "abb2bf", token: "punctuation" },
        // Enhanced contrast for some tokens
        { foreground: "56b6c2", token: "support.type" },
        { foreground: "56b6c2", token: "support.class" },
        { foreground: "be5046", token: "invalid" },
        { foreground: "e06c75", token: "markup.deleted" },
        { foreground: "98c379", token: "markup.inserted" },
    ],
    colors: {
        "editor.foreground": "#abb2bf",
        "editor.background": "#1e2127",
        "editor.selectionBackground": "#323842",
        "editor.lineHighlightBackground": "#181a1f",
        "editorCursor.foreground": "#528bff",
        "editorWhitespace.foreground": "#3b4048",
        "editorIndentGuide.background": "#3b4048",
        "editorIndentGuide.activeBackground": "#4b5362",
        "editor.findMatchBackground": "#42557b",
        "editor.findMatchHighlightBackground": "#314365",
    },
}

// Monokai One Dark Vivid Theme
export const monokaiOneDarkVividTheme = {
    base: "vs-dark",
    inherit: true,
    rules: [
        { background: "1d1e22", token: "" },
        { foreground: "5c636f", token: "comment" },
        { foreground: "ff6ac1", token: "keyword" },
        { foreground: "ff6ac1", token: "storage" },
        { foreground: "ff6ac1", token: "storage.type" },
        { foreground: "e5c07b", token: "entity.name.class" },
        { foreground: "e5c07b", token: "entity.name.type.class" },
        { foreground: "a8ff60", token: "string" },
        { foreground: "a8ff60", token: "constant.other.symbol" },
        { foreground: "61afef", token: "entity.name.function" },
        { foreground: "61afef", token: "meta.function-call" },
        { foreground: "61afef", token: "support.function" },
        { foreground: "ff9d45", token: "constant.numeric" },
        { foreground: "ff9d45", token: "constant.language" },
        { foreground: "ff5c57", token: "variable" },
        { foreground: "ff5c57", token: "support.variable" },
        { foreground: "ff5c57", token: "entity.name.tag" },
        { foreground: "ff9d45", token: "entity.other.attribute-name" },
        { foreground: "f8f8f2", token: "punctuation" },
        // Additional syntax highlighting
        { foreground: "5aebff", token: "support.type" },
        { foreground: "5aebff", token: "support.class" },
        { foreground: "ff5c57", token: "invalid" },
        { foreground: "ff5c57", token: "markup.deleted" },
        { foreground: "a8ff60", token: "markup.inserted" },
        { foreground: "ffff00", token: "markup.changed" },
        { foreground: "ff6ac1", token: "entity.other.inherited-class" },
        { foreground: "5aebff", token: "support.constant" },
        { foreground: "ff9d45", token: "support.type.property-name" },
    ],
    colors: {
        "editor.foreground": "#f8f8f2",
        "editor.background": "#1d1e22",
        "editor.selectionBackground": "#3a404e",
        "editor.lineHighlightBackground": "#16171b",
        "editorCursor.foreground": "#5aebff",
        "editorWhitespace.foreground": "#343642",
        "editorIndentGuide.background": "#343642",
        "editorIndentGuide.activeBackground": "#4b5362",
        "editor.findMatchBackground": "#42557b",
        "editor.findMatchHighlightBackground": "#314365",
        "editorLineNumber.foreground": "#4b5362",
        "editorLineNumber.activeForeground": "#8a95a5",
        "editorBracketMatch.border": "#ff6ac1",
        "editorBracketMatch.background": "#1d1e22",
    },
}

// GitHub Light Theme
export const githubLightTheme = {
    base: "vs",
    inherit: true,
    rules: [
        { background: "ffffff", token: "" },
        { foreground: "6a737d", token: "comment" },
        { foreground: "d73a49", token: "keyword" },
        { foreground: "d73a49", token: "storage" },
        { foreground: "d73a49", token: "storage.type" },
        { foreground: "6f42c1", token: "entity.name.class" },
        { foreground: "6f42c1", token: "entity.name.type.class" },
        { foreground: "032f62", token: "string" },
        { foreground: "032f62", token: "constant.other.symbol" },
        { foreground: "6f42c1", token: "entity.name.function" },
        { foreground: "6f42c1", token: "meta.function-call" },
        { foreground: "005cc5", token: "support.function" },
        { foreground: "005cc5", token: "constant.numeric" },
        { foreground: "005cc5", token: "constant.language" },
        { foreground: "24292e", token: "variable" },
        { foreground: "24292e", token: "support.variable" },
        { foreground: "22863a", token: "entity.name.tag" },
        { foreground: "6f42c1", token: "entity.other.attribute-name" },
        { foreground: "24292e", token: "punctuation" },
        // Additional syntax highlighting for better distinction
        { foreground: "e36209", token: "support.type" },
        { foreground: "e36209", token: "support.class" },
        { foreground: "b31d28", token: "invalid" },
        { foreground: "b31d28", token: "markup.deleted" },
        { foreground: "22863a", token: "markup.inserted" },
        { foreground: "e36209", token: "markup.changed" },
        { foreground: "6f42c1", token: "entity.other.inherited-class" },
        { foreground: "005cc5", token: "support.constant" },
        { foreground: "005cc5", token: "support.type.property-name" },
    ],
    colors: {
        "editor.foreground": "#24292e",
        "editor.background": "#ffffff",
        "editor.selectionBackground": "#c8c8fa",
        "editor.lineHighlightBackground": "#f6f8fa",
        "editorCursor.foreground": "#044289",
        "editorWhitespace.foreground": "#e1e4e8",
        "editorIndentGuide.background": "#e1e4e8",
        "editorIndentGuide.activeBackground": "#d1d5da",
        "editor.findMatchBackground": "#ffdf5d",
        "editor.findMatchHighlightBackground": "#ffdf5d80",
        "editorLineNumber.foreground": "#bbb",
        "editorLineNumber.activeForeground": "#444",
        "editorBracketMatch.border": "#6f42c1",
        "editorBracketMatch.background": "#f6f8fa",
    },
}
