drop function if exists "public"."add_credits_to_user"(user_id uuid, credits numeric);

create table "public"."payment_errors" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "cause" text,
    "payment_ref" text,
    "order_id" text,
    "user_id" uuid default gen_random_uuid(),
    "error_text" text
);


alter table "public"."payment_errors" enable row level security;

CREATE UNIQUE INDEX payment_errors_pkey ON public.payment_errors USING btree (id);

alter table "public"."payment_errors" add constraint "payment_errors_pkey" PRIMARY KEY using index "payment_errors_pkey";

alter table "public"."payment_errors" add constraint "payment_errors_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profiles(user_id) ON DELETE SET NULL not valid;

alter table "public"."payment_errors" validate constraint "payment_errors_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.add_credits_to_user(p_user_id uuid, credits numeric)
 RETURNS void
 LANGUAGE plpgsql
AS $function$BEGIN

  UPDATE user_profiles
  SET credit_balance = credit_balance + credits
  WHERE user_id = p_user_id;
  
END;$function$
;

grant delete on table "public"."payment_errors" to "anon";

grant insert on table "public"."payment_errors" to "anon";

grant references on table "public"."payment_errors" to "anon";

grant select on table "public"."payment_errors" to "anon";

grant trigger on table "public"."payment_errors" to "anon";

grant truncate on table "public"."payment_errors" to "anon";

grant update on table "public"."payment_errors" to "anon";

grant delete on table "public"."payment_errors" to "authenticated";

grant insert on table "public"."payment_errors" to "authenticated";

grant references on table "public"."payment_errors" to "authenticated";

grant select on table "public"."payment_errors" to "authenticated";

grant trigger on table "public"."payment_errors" to "authenticated";

grant truncate on table "public"."payment_errors" to "authenticated";

grant update on table "public"."payment_errors" to "authenticated";

grant delete on table "public"."payment_errors" to "service_role";

grant insert on table "public"."payment_errors" to "service_role";

grant references on table "public"."payment_errors" to "service_role";

grant select on table "public"."payment_errors" to "service_role";

grant trigger on table "public"."payment_errors" to "service_role";

grant truncate on table "public"."payment_errors" to "service_role";

grant update on table "public"."payment_errors" to "service_role";


