create table "public"."mindmap_node_explanation" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "node_id" text not null default ''::text,
    "content" text not null default ''::text,
    "mindmap_id" bigint,
    "author_id" uuid
);


alter table "public"."mindmap_node_explanation" enable row level security;

alter table "public"."mindmaps" alter column "publishing_status" set default 'DRAFT'::publishing_status;

alter table "public"."mindmaps" alter column "publishing_status" set not null;

CREATE INDEX mindmaps_author_id_idx ON public.mindmaps USING btree (author_id);

CREATE INDEX minmap_node_explanation_author_id_idx ON public.mindmap_node_explanation USING btree (author_id);

CREATE INDEX minmap_node_explanation_mindmap_id_idx ON public.mindmap_node_explanation USING btree (mindmap_id);

CREATE INDEX minmap_node_explanation_node_id_idx ON public.mindmap_node_explanation USING btree (node_id);

CREATE UNIQUE INDEX minmap_node_explanation_node_id_key ON public.mindmap_node_explanation USING btree (node_id);

CREATE UNIQUE INDEX minmap_node_explanation_pkey ON public.mindmap_node_explanation USING btree (id);

alter table "public"."mindmap_node_explanation" add constraint "minmap_node_explanation_pkey" PRIMARY KEY using index "minmap_node_explanation_pkey";

alter table "public"."mindmap_node_explanation" add constraint "minmap_node_explanation_author_id_fkey" FOREIGN KEY (author_id) REFERENCES user_profiles(user_id) ON DELETE CASCADE not valid;

alter table "public"."mindmap_node_explanation" validate constraint "minmap_node_explanation_author_id_fkey";

alter table "public"."mindmap_node_explanation" add constraint "minmap_node_explanation_mindmap_id_fkey" FOREIGN KEY (mindmap_id) REFERENCES mindmaps(id) ON DELETE CASCADE not valid;

alter table "public"."mindmap_node_explanation" validate constraint "minmap_node_explanation_mindmap_id_fkey";

alter table "public"."mindmap_node_explanation" add constraint "minmap_node_explanation_node_id_key" UNIQUE using index "minmap_node_explanation_node_id_key";

grant delete on table "public"."mindmap_node_explanation" to "anon";

grant insert on table "public"."mindmap_node_explanation" to "anon";

grant references on table "public"."mindmap_node_explanation" to "anon";

grant select on table "public"."mindmap_node_explanation" to "anon";

grant trigger on table "public"."mindmap_node_explanation" to "anon";

grant truncate on table "public"."mindmap_node_explanation" to "anon";

grant update on table "public"."mindmap_node_explanation" to "anon";

grant delete on table "public"."mindmap_node_explanation" to "authenticated";

grant insert on table "public"."mindmap_node_explanation" to "authenticated";

grant references on table "public"."mindmap_node_explanation" to "authenticated";

grant select on table "public"."mindmap_node_explanation" to "authenticated";

grant trigger on table "public"."mindmap_node_explanation" to "authenticated";

grant truncate on table "public"."mindmap_node_explanation" to "authenticated";

grant update on table "public"."mindmap_node_explanation" to "authenticated";

grant delete on table "public"."mindmap_node_explanation" to "service_role";

grant insert on table "public"."mindmap_node_explanation" to "service_role";

grant references on table "public"."mindmap_node_explanation" to "service_role";

grant select on table "public"."mindmap_node_explanation" to "service_role";

grant trigger on table "public"."mindmap_node_explanation" to "service_role";

grant truncate on table "public"."mindmap_node_explanation" to "service_role";

grant update on table "public"."mindmap_node_explanation" to "service_role";


