create type "public"."publishing_status" as enum ('DRAFT', 'PUBLISHED', 'ARCHIVED');

create type "public"."quiz_question_types" as enum ('MULTIPLE_CHOICE', 'MATCHING_PAIRS', 'DEBUG_CODE', 'CODE_COMPLETION');

create type "public"."user_role_types" as enum ('ADMIN', 'USER');

create table "public"."quiz_submission_answers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "quiz_submission" bigint,
    "seconds_spent" numeric,
    "is_answered_correctly" boolean,
    "is_skipped" boolean not null default false,
    "failed_attempts" bigint default '0'::bigint,
    "responses" jsonb default '[]'::jsonb,
    "question" bigint
);


alter table "public"."quiz_submission_answers" enable row level security;

create table "public"."quiz_submissions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "seconds_spent" numeric,
    "quiz" bigint,
    "user" uuid default gen_random_uuid()
);


alter table "public"."quiz_submissions" enable row level security;

create table "public"."quizzes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "category" bigint,
    "image" text,
    "description" text default ''::text,
    "publishing_status" publishing_status not null default 'DRAFT'::publishing_status,
    "author_id" uuid
);


alter table "public"."quizzes" enable row level security;

create table "public"."quizzes_categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "image" text,
    "description" text,
    "publishing_status" publishing_status default 'DRAFT'::publishing_status
);


alter table "public"."quizzes_categories" enable row level security;

create table "public"."quizzes_questions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "question" text not null default ''::text,
    "image" text default ''::text,
    "quiz" bigint,
    "content" jsonb,
    "type" quiz_question_types,
    "layout" text default 'vertical'::text
);


alter table "public"."quizzes_questions" enable row level security;

create table "public"."users_profiles" (
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default gen_random_uuid(),
    "user_role" user_role_types default 'USER'::user_role_types
);


alter table "public"."users_profiles" enable row level security;

CREATE UNIQUE INDEX quiz_pkey ON public.quizzes USING btree (id);

CREATE UNIQUE INDEX quiz_submission_answers_pkey ON public.quiz_submission_answers USING btree (id);

CREATE UNIQUE INDEX quiz_submissions_pkey ON public.quiz_submissions USING btree (id);

CREATE UNIQUE INDEX "quizzes-categories_pkey" ON public.quizzes_categories USING btree (id);

CREATE UNIQUE INDEX "quizzes-question_pkey" ON public.quizzes_questions USING btree (id);

CREATE INDEX quizzes_category_idx ON public.quizzes USING btree (category);

CREATE INDEX quizzes_questions_quiz_idx ON public.quizzes_questions USING btree (quiz);

CREATE UNIQUE INDEX users_to_roles_pkey ON public.users_profiles USING btree (user_id);

alter table "public"."quiz_submission_answers" add constraint "quiz_submission_answers_pkey" PRIMARY KEY using index "quiz_submission_answers_pkey";

alter table "public"."quiz_submissions" add constraint "quiz_submissions_pkey" PRIMARY KEY using index "quiz_submissions_pkey";

alter table "public"."quizzes" add constraint "quiz_pkey" PRIMARY KEY using index "quiz_pkey";

alter table "public"."quizzes_categories" add constraint "quizzes-categories_pkey" PRIMARY KEY using index "quizzes-categories_pkey";

alter table "public"."quizzes_questions" add constraint "quizzes-question_pkey" PRIMARY KEY using index "quizzes-question_pkey";

alter table "public"."users_profiles" add constraint "users_to_roles_pkey" PRIMARY KEY using index "users_to_roles_pkey";

alter table "public"."quiz_submission_answers" add constraint "quiz_submission_answers_question_fkey" FOREIGN KEY (question) REFERENCES quizzes_questions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."quiz_submission_answers" validate constraint "quiz_submission_answers_question_fkey";

alter table "public"."quiz_submission_answers" add constraint "quiz_submission_answers_quiz_submission_fkey" FOREIGN KEY (quiz_submission) REFERENCES quiz_submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."quiz_submission_answers" validate constraint "quiz_submission_answers_quiz_submission_fkey";

alter table "public"."quiz_submissions" add constraint "quiz_submissions_quiz_id_fkey" FOREIGN KEY (quiz) REFERENCES quizzes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."quiz_submissions" validate constraint "quiz_submissions_quiz_id_fkey";

alter table "public"."quiz_submissions" add constraint "quiz_submissions_user_id_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."quiz_submissions" validate constraint "quiz_submissions_user_id_fkey";

alter table "public"."quizzes" add constraint "quizzes_author_id_fkey" FOREIGN KEY (author_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."quizzes" validate constraint "quizzes_author_id_fkey";

alter table "public"."quizzes" add constraint "quizzes_category_fkey" FOREIGN KEY (category) REFERENCES quizzes_categories(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."quizzes" validate constraint "quizzes_category_fkey";

alter table "public"."quizzes_questions" add constraint "quizzes-questions_quiz_fkey" FOREIGN KEY (quiz) REFERENCES quizzes(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."quizzes_questions" validate constraint "quizzes-questions_quiz_fkey";

alter table "public"."users_profiles" add constraint "users_to_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."users_profiles" validate constraint "users_to_roles_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user_role()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
 
  insert into "public"."users_to_roles" (user_id ,"user_role")
  values (new.id, 'ADMIN'); 
    return new;
end;
$function$
;

grant delete on table "public"."quiz_submission_answers" to "anon";

grant insert on table "public"."quiz_submission_answers" to "anon";

grant references on table "public"."quiz_submission_answers" to "anon";

grant select on table "public"."quiz_submission_answers" to "anon";

grant trigger on table "public"."quiz_submission_answers" to "anon";

grant truncate on table "public"."quiz_submission_answers" to "anon";

grant update on table "public"."quiz_submission_answers" to "anon";

grant delete on table "public"."quiz_submission_answers" to "authenticated";

grant insert on table "public"."quiz_submission_answers" to "authenticated";

grant references on table "public"."quiz_submission_answers" to "authenticated";

grant select on table "public"."quiz_submission_answers" to "authenticated";

grant trigger on table "public"."quiz_submission_answers" to "authenticated";

grant truncate on table "public"."quiz_submission_answers" to "authenticated";

grant update on table "public"."quiz_submission_answers" to "authenticated";

grant delete on table "public"."quiz_submission_answers" to "service_role";

grant insert on table "public"."quiz_submission_answers" to "service_role";

grant references on table "public"."quiz_submission_answers" to "service_role";

grant select on table "public"."quiz_submission_answers" to "service_role";

grant trigger on table "public"."quiz_submission_answers" to "service_role";

grant truncate on table "public"."quiz_submission_answers" to "service_role";

grant update on table "public"."quiz_submission_answers" to "service_role";

grant delete on table "public"."quiz_submissions" to "anon";

grant insert on table "public"."quiz_submissions" to "anon";

grant references on table "public"."quiz_submissions" to "anon";

grant select on table "public"."quiz_submissions" to "anon";

grant trigger on table "public"."quiz_submissions" to "anon";

grant truncate on table "public"."quiz_submissions" to "anon";

grant update on table "public"."quiz_submissions" to "anon";

grant delete on table "public"."quiz_submissions" to "authenticated";

grant insert on table "public"."quiz_submissions" to "authenticated";

grant references on table "public"."quiz_submissions" to "authenticated";

grant select on table "public"."quiz_submissions" to "authenticated";

grant trigger on table "public"."quiz_submissions" to "authenticated";

grant truncate on table "public"."quiz_submissions" to "authenticated";

grant update on table "public"."quiz_submissions" to "authenticated";

grant delete on table "public"."quiz_submissions" to "service_role";

grant insert on table "public"."quiz_submissions" to "service_role";

grant references on table "public"."quiz_submissions" to "service_role";

grant select on table "public"."quiz_submissions" to "service_role";

grant trigger on table "public"."quiz_submissions" to "service_role";

grant truncate on table "public"."quiz_submissions" to "service_role";

grant update on table "public"."quiz_submissions" to "service_role";

grant delete on table "public"."quizzes" to "anon";

grant insert on table "public"."quizzes" to "anon";

grant references on table "public"."quizzes" to "anon";

grant select on table "public"."quizzes" to "anon";

grant trigger on table "public"."quizzes" to "anon";

grant truncate on table "public"."quizzes" to "anon";

grant update on table "public"."quizzes" to "anon";

grant delete on table "public"."quizzes" to "authenticated";

grant insert on table "public"."quizzes" to "authenticated";

grant references on table "public"."quizzes" to "authenticated";

grant select on table "public"."quizzes" to "authenticated";

grant trigger on table "public"."quizzes" to "authenticated";

grant truncate on table "public"."quizzes" to "authenticated";

grant update on table "public"."quizzes" to "authenticated";

grant delete on table "public"."quizzes" to "service_role";

grant insert on table "public"."quizzes" to "service_role";

grant references on table "public"."quizzes" to "service_role";

grant select on table "public"."quizzes" to "service_role";

grant trigger on table "public"."quizzes" to "service_role";

grant truncate on table "public"."quizzes" to "service_role";

grant update on table "public"."quizzes" to "service_role";

grant delete on table "public"."quizzes_categories" to "anon";

grant insert on table "public"."quizzes_categories" to "anon";

grant references on table "public"."quizzes_categories" to "anon";

grant select on table "public"."quizzes_categories" to "anon";

grant trigger on table "public"."quizzes_categories" to "anon";

grant truncate on table "public"."quizzes_categories" to "anon";

grant update on table "public"."quizzes_categories" to "anon";

grant delete on table "public"."quizzes_categories" to "authenticated";

grant insert on table "public"."quizzes_categories" to "authenticated";

grant references on table "public"."quizzes_categories" to "authenticated";

grant select on table "public"."quizzes_categories" to "authenticated";

grant trigger on table "public"."quizzes_categories" to "authenticated";

grant truncate on table "public"."quizzes_categories" to "authenticated";

grant update on table "public"."quizzes_categories" to "authenticated";

grant delete on table "public"."quizzes_categories" to "service_role";

grant insert on table "public"."quizzes_categories" to "service_role";

grant references on table "public"."quizzes_categories" to "service_role";

grant select on table "public"."quizzes_categories" to "service_role";

grant trigger on table "public"."quizzes_categories" to "service_role";

grant truncate on table "public"."quizzes_categories" to "service_role";

grant update on table "public"."quizzes_categories" to "service_role";

grant delete on table "public"."quizzes_questions" to "anon";

grant insert on table "public"."quizzes_questions" to "anon";

grant references on table "public"."quizzes_questions" to "anon";

grant select on table "public"."quizzes_questions" to "anon";

grant trigger on table "public"."quizzes_questions" to "anon";

grant truncate on table "public"."quizzes_questions" to "anon";

grant update on table "public"."quizzes_questions" to "anon";

grant delete on table "public"."quizzes_questions" to "authenticated";

grant insert on table "public"."quizzes_questions" to "authenticated";

grant references on table "public"."quizzes_questions" to "authenticated";

grant select on table "public"."quizzes_questions" to "authenticated";

grant trigger on table "public"."quizzes_questions" to "authenticated";

grant truncate on table "public"."quizzes_questions" to "authenticated";

grant update on table "public"."quizzes_questions" to "authenticated";

grant delete on table "public"."quizzes_questions" to "service_role";

grant insert on table "public"."quizzes_questions" to "service_role";

grant references on table "public"."quizzes_questions" to "service_role";

grant select on table "public"."quizzes_questions" to "service_role";

grant trigger on table "public"."quizzes_questions" to "service_role";

grant truncate on table "public"."quizzes_questions" to "service_role";

grant update on table "public"."quizzes_questions" to "service_role";

grant delete on table "public"."users_profiles" to "anon";

grant insert on table "public"."users_profiles" to "anon";

grant references on table "public"."users_profiles" to "anon";

grant select on table "public"."users_profiles" to "anon";

grant trigger on table "public"."users_profiles" to "anon";

grant truncate on table "public"."users_profiles" to "anon";

grant update on table "public"."users_profiles" to "anon";

grant delete on table "public"."users_profiles" to "authenticated";

grant insert on table "public"."users_profiles" to "authenticated";

grant references on table "public"."users_profiles" to "authenticated";

grant select on table "public"."users_profiles" to "authenticated";

grant trigger on table "public"."users_profiles" to "authenticated";

grant truncate on table "public"."users_profiles" to "authenticated";

grant update on table "public"."users_profiles" to "authenticated";

grant delete on table "public"."users_profiles" to "service_role";

grant insert on table "public"."users_profiles" to "service_role";

grant references on table "public"."users_profiles" to "service_role";

grant select on table "public"."users_profiles" to "service_role";

grant trigger on table "public"."users_profiles" to "service_role";

grant truncate on table "public"."users_profiles" to "service_role";

grant update on table "public"."users_profiles" to "service_role";

create policy "Enable delete for admins only"
on "public"."quiz_submission_answers"
as permissive
for delete
to authenticated
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable insert for authenticated users only"
on "public"."quiz_submission_answers"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for admins only"
on "public"."quiz_submission_answers"
as permissive
for select
to authenticated
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable update for admins only"
on "public"."quiz_submission_answers"
as permissive
for update
to authenticated
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable delete for admins only"
on "public"."quiz_submissions"
as permissive
for delete
to authenticated
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable insert for authenticated users only"
on "public"."quiz_submissions"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for admins only"
on "public"."quiz_submissions"
as permissive
for select
to authenticated
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable update for admins only"
on "public"."quiz_submissions"
as permissive
for update
to authenticated
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable delete for admins only"
on "public"."quizzes"
as permissive
for delete
to public
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable insert for admins only"
on "public"."quizzes"
as permissive
for insert
to authenticated
with check ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable read access for authenticated users"
on "public"."quizzes"
as permissive
for select
to authenticated
using (true);


create policy "Enable update for admins only"
on "public"."quizzes"
as permissive
for update
to authenticated
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable delete for admins only"
on "public"."quizzes_categories"
as permissive
for delete
to authenticated
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable insert for admins only"
on "public"."quizzes_categories"
as permissive
for insert
to authenticated
with check ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable read access for authenticated users"
on "public"."quizzes_categories"
as permissive
for select
to authenticated
using (true);


create policy "Enable update for admins only"
on "public"."quizzes_categories"
as permissive
for update
to authenticated
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types))
with check ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable delete for admins only"
on "public"."quizzes_questions"
as permissive
for insert
to authenticated
with check ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable read access for authenticated users"
on "public"."quizzes_questions"
as permissive
for select
to authenticated
using (true);


create policy "enable delete for admins only"
on "public"."quizzes_questions"
as permissive
for delete
to public
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "enable update for admins only"
on "public"."quizzes_questions"
as permissive
for update
to authenticated
using ((( SELECT users_profiles.user_role
   FROM users_profiles
  WHERE (users_profiles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "enable read only for authenticated users"
on "public"."users_profiles"
as permissive
for select
to authenticated
using (true);



