create type "public"."publishing_status" as enum ('DRAFT', 'PUBLISHED', 'ARCHIVED');

drop policy "Enable delete for admins only" on "public"."categories";

drop policy "Enable insert for admins only" on "public"."categories";

drop policy "Enable read access for authenticated users" on "public"."categories";

drop policy "Enable update for admins only" on "public"."categories";

revoke delete on table "public"."categories" from "anon";

revoke insert on table "public"."categories" from "anon";

revoke references on table "public"."categories" from "anon";

revoke select on table "public"."categories" from "anon";

revoke trigger on table "public"."categories" from "anon";

revoke truncate on table "public"."categories" from "anon";

revoke update on table "public"."categories" from "anon";

revoke delete on table "public"."categories" from "authenticated";

revoke insert on table "public"."categories" from "authenticated";

revoke references on table "public"."categories" from "authenticated";

revoke select on table "public"."categories" from "authenticated";

revoke trigger on table "public"."categories" from "authenticated";

revoke truncate on table "public"."categories" from "authenticated";

revoke update on table "public"."categories" from "authenticated";

revoke delete on table "public"."categories" from "service_role";

revoke insert on table "public"."categories" from "service_role";

revoke references on table "public"."categories" from "service_role";

revoke select on table "public"."categories" from "service_role";

revoke trigger on table "public"."categories" from "service_role";

revoke truncate on table "public"."categories" from "service_role";

revoke update on table "public"."categories" from "service_role";

alter table "public"."quizzes" drop constraint "quizzes_category_fkey";

alter table "public"."categories" drop constraint "quizzes-categories_pkey";

drop index if exists "public"."quizzes-categories_pkey";

drop table "public"."categories";

create table "public"."quizzes_categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "image" text,
    "description" text
);


alter table "public"."quizzes_categories" enable row level security;

alter table "public"."quizzes" add column "publishing_status" publishing_status not null default 'DRAFT'::publishing_status;

CREATE UNIQUE INDEX "quizzes-categories_pkey" ON public.quizzes_categories USING btree (id);

alter table "public"."quizzes_categories" add constraint "quizzes-categories_pkey" PRIMARY KEY using index "quizzes-categories_pkey";

alter table "public"."quizzes" add constraint "quizzes_category_fkey" FOREIGN KEY (category) REFERENCES quizzes_categories(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."quizzes" validate constraint "quizzes_category_fkey";

grant delete on table "public"."quizzes_categories" to "anon";

grant insert on table "public"."quizzes_categories" to "anon";

grant references on table "public"."quizzes_categories" to "anon";

grant select on table "public"."quizzes_categories" to "anon";

grant trigger on table "public"."quizzes_categories" to "anon";

grant truncate on table "public"."quizzes_categories" to "anon";

grant update on table "public"."quizzes_categories" to "anon";

grant delete on table "public"."quizzes_categories" to "authenticated";

grant insert on table "public"."quizzes_categories" to "authenticated";

grant references on table "public"."quizzes_categories" to "authenticated";

grant select on table "public"."quizzes_categories" to "authenticated";

grant trigger on table "public"."quizzes_categories" to "authenticated";

grant truncate on table "public"."quizzes_categories" to "authenticated";

grant update on table "public"."quizzes_categories" to "authenticated";

grant delete on table "public"."quizzes_categories" to "service_role";

grant insert on table "public"."quizzes_categories" to "service_role";

grant references on table "public"."quizzes_categories" to "service_role";

grant select on table "public"."quizzes_categories" to "service_role";

grant trigger on table "public"."quizzes_categories" to "service_role";

grant truncate on table "public"."quizzes_categories" to "service_role";

grant update on table "public"."quizzes_categories" to "service_role";

create policy "Enable delete for admins only"
on "public"."quizzes_categories"
as permissive
for delete
to authenticated
using ((( SELECT users_to_roles.user_role
   FROM users_to_roles
  WHERE (users_to_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable insert for admins only"
on "public"."quizzes_categories"
as permissive
for insert
to authenticated
with check ((( SELECT users_to_roles.user_role
   FROM users_to_roles
  WHERE (users_to_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));


create policy "Enable read access for authenticated users"
on "public"."quizzes_categories"
as permissive
for select
to authenticated
using (true);


create policy "Enable update for admins only"
on "public"."quizzes_categories"
as permissive
for update
to authenticated
using ((( SELECT users_to_roles.user_role
   FROM users_to_roles
  WHERE (users_to_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types))
with check ((( SELECT users_to_roles.user_role
   FROM users_to_roles
  WHERE (users_to_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types));



