drop policy "authenticated can insert data" on "public"."mindamps";

drop policy "service role can do anything" on "public"."mindamps";

drop policy "user can delete their data / admin delete all" on "public"."mindamps";

drop policy "users can update their data / admin update all" on "public"."mindamps";

drop policy "users can view their data / admin view all" on "public"."mindamps";

revoke delete on table "public"."mindamps" from "anon";

revoke insert on table "public"."mindamps" from "anon";

revoke references on table "public"."mindamps" from "anon";

revoke select on table "public"."mindamps" from "anon";

revoke trigger on table "public"."mindamps" from "anon";

revoke truncate on table "public"."mindamps" from "anon";

revoke update on table "public"."mindamps" from "anon";

revoke delete on table "public"."mindamps" from "authenticated";

revoke insert on table "public"."mindamps" from "authenticated";

revoke references on table "public"."mindamps" from "authenticated";

revoke select on table "public"."mindamps" from "authenticated";

revoke trigger on table "public"."mindamps" from "authenticated";

revoke truncate on table "public"."mindamps" from "authenticated";

revoke update on table "public"."mindamps" from "authenticated";

revoke delete on table "public"."mindamps" from "service_role";

revoke insert on table "public"."mindamps" from "service_role";

revoke references on table "public"."mindamps" from "service_role";

revoke select on table "public"."mindamps" from "service_role";

revoke trigger on table "public"."mindamps" from "service_role";

revoke truncate on table "public"."mindamps" from "service_role";

revoke update on table "public"."mindamps" from "service_role";

alter table "public"."mindamps" drop constraint "mindamps_author_id_fkey";

alter table "public"."mindamps" drop constraint "mindamps_pkey";

drop index if exists "public"."mindamps_pkey";

drop table "public"."mindamps";

create table "public"."mindmaps" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text default ''::text,
    "image" text,
    "publishing_status" publishing_status,
    "author_id" uuid default gen_random_uuid(),
    "nodes" jsonb,
    "edges" jsonb
);


alter table "public"."mindmaps" enable row level security;

CREATE UNIQUE INDEX mindamps_pkey ON public.mindmaps USING btree (id);

alter table "public"."mindmaps" add constraint "mindamps_pkey" PRIMARY KEY using index "mindamps_pkey";

alter table "public"."mindmaps" add constraint "mindamps_author_id_fkey" FOREIGN KEY (author_id) REFERENCES user_profiles(user_id) ON DELETE CASCADE not valid;

alter table "public"."mindmaps" validate constraint "mindamps_author_id_fkey";

grant delete on table "public"."mindmaps" to "anon";

grant insert on table "public"."mindmaps" to "anon";

grant references on table "public"."mindmaps" to "anon";

grant select on table "public"."mindmaps" to "anon";

grant trigger on table "public"."mindmaps" to "anon";

grant truncate on table "public"."mindmaps" to "anon";

grant update on table "public"."mindmaps" to "anon";

grant delete on table "public"."mindmaps" to "authenticated";

grant insert on table "public"."mindmaps" to "authenticated";

grant references on table "public"."mindmaps" to "authenticated";

grant select on table "public"."mindmaps" to "authenticated";

grant trigger on table "public"."mindmaps" to "authenticated";

grant truncate on table "public"."mindmaps" to "authenticated";

grant update on table "public"."mindmaps" to "authenticated";

grant delete on table "public"."mindmaps" to "service_role";

grant insert on table "public"."mindmaps" to "service_role";

grant references on table "public"."mindmaps" to "service_role";

grant select on table "public"."mindmaps" to "service_role";

grant trigger on table "public"."mindmaps" to "service_role";

grant truncate on table "public"."mindmaps" to "service_role";

grant update on table "public"."mindmaps" to "service_role";

create policy "authenticated can insert data"
on "public"."mindmaps"
as permissive
for insert
to authenticated
with check (true);


create policy "service role can do anything"
on "public"."mindmaps"
as permissive
for all
to service_role
using (true);


create policy "user can delete their data / admin delete all"
on "public"."mindmaps"
as permissive
for delete
to authenticated
using (((( SELECT auth.uid() AS uid) = author_id) OR (( SELECT user_roles.user_role
   FROM user_roles
  WHERE (user_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types)));


create policy "users can update their data / admin update all"
on "public"."mindmaps"
as permissive
for update
to authenticated
using (((( SELECT auth.uid() AS uid) = author_id) OR (( SELECT user_roles.user_role
   FROM user_roles
  WHERE (user_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types)));


create policy "users can view their data / admin view all"
on "public"."mindmaps"
as permissive
for select
to authenticated
using (((( SELECT auth.uid() AS uid) = author_id) OR (( SELECT user_roles.user_role
   FROM user_roles
  WHERE (user_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types)));



