create table "public"."quizzes_refunds" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "cause" text,
    "quiz_id" bigint
);


alter table "public"."quizzes_refunds" enable row level security;

alter table "public"."quizzes" add column "credit_cost" numeric default '0'::numeric;

CREATE UNIQUE INDEX quizzes_refunds_pkey ON public.quizzes_refunds USING btree (id);

alter table "public"."quizzes_refunds" add constraint "quizzes_refunds_pkey" PRIMARY KEY using index "quizzes_refunds_pkey";

alter table "public"."quizzes_refunds" add constraint "quizzes_refunds_quiz_id_fkey" FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."quizzes_refunds" validate constraint "quizzes_refunds_quiz_id_fkey";

grant delete on table "public"."quizzes_refunds" to "anon";

grant insert on table "public"."quizzes_refunds" to "anon";

grant references on table "public"."quizzes_refunds" to "anon";

grant select on table "public"."quizzes_refunds" to "anon";

grant trigger on table "public"."quizzes_refunds" to "anon";

grant truncate on table "public"."quizzes_refunds" to "anon";

grant update on table "public"."quizzes_refunds" to "anon";

grant delete on table "public"."quizzes_refunds" to "authenticated";

grant insert on table "public"."quizzes_refunds" to "authenticated";

grant references on table "public"."quizzes_refunds" to "authenticated";

grant select on table "public"."quizzes_refunds" to "authenticated";

grant trigger on table "public"."quizzes_refunds" to "authenticated";

grant truncate on table "public"."quizzes_refunds" to "authenticated";

grant update on table "public"."quizzes_refunds" to "authenticated";

grant delete on table "public"."quizzes_refunds" to "service_role";

grant insert on table "public"."quizzes_refunds" to "service_role";

grant references on table "public"."quizzes_refunds" to "service_role";

grant select on table "public"."quizzes_refunds" to "service_role";

grant trigger on table "public"."quizzes_refunds" to "service_role";

grant truncate on table "public"."quizzes_refunds" to "service_role";

grant update on table "public"."quizzes_refunds" to "service_role";

create policy "Service role can  do anything"
on "public"."quizzes_refunds"
as permissive
for all
to service_role
using (true);



