create table "public"."questions_hints" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "question_id" bigint,
    "content" text,
    "name" text,
    "author_id" uuid
);


alter table "public"."questions_hints" enable row level security;

CREATE UNIQUE INDEX questions_hints_pkey ON public.questions_hints USING btree (id);

alter table "public"."questions_hints" add constraint "questions_hints_pkey" PRIMARY KEY using index "questions_hints_pkey";

alter table "public"."questions_hints" add constraint "questions_hints_author_id_fkey" FOREIGN KEY (author_id) REFERENCES user_profiles(user_id) ON DELETE SET NULL not valid;

alter table "public"."questions_hints" validate constraint "questions_hints_author_id_fkey";

alter table "public"."questions_hints" add constraint "questions_hints_question_id_fkey" FOREIGN KEY (question_id) REFERENCES quizzes_questions(id) ON DELETE CASCADE not valid;

alter table "public"."questions_hints" validate constraint "questions_hints_question_id_fkey";

grant delete on table "public"."questions_hints" to "anon";

grant insert on table "public"."questions_hints" to "anon";

grant references on table "public"."questions_hints" to "anon";

grant select on table "public"."questions_hints" to "anon";

grant trigger on table "public"."questions_hints" to "anon";

grant truncate on table "public"."questions_hints" to "anon";

grant update on table "public"."questions_hints" to "anon";

grant delete on table "public"."questions_hints" to "authenticated";

grant insert on table "public"."questions_hints" to "authenticated";

grant references on table "public"."questions_hints" to "authenticated";

grant select on table "public"."questions_hints" to "authenticated";

grant trigger on table "public"."questions_hints" to "authenticated";

grant truncate on table "public"."questions_hints" to "authenticated";

grant update on table "public"."questions_hints" to "authenticated";

grant delete on table "public"."questions_hints" to "service_role";

grant insert on table "public"."questions_hints" to "service_role";

grant references on table "public"."questions_hints" to "service_role";

grant select on table "public"."questions_hints" to "service_role";

grant trigger on table "public"."questions_hints" to "service_role";

grant truncate on table "public"."questions_hints" to "service_role";

grant update on table "public"."questions_hints" to "service_role";

create policy "Service can do anything"
on "public"."questions_hints"
as permissive
for all
to service_role
using (true);


create policy "all users can read hints"
on "public"."questions_hints"
as permissive
for select
to authenticated
using (true);


create policy "user can attach to their quizzes / admin can attach to all"
on "public"."questions_hints"
as permissive
for insert
to public
with check (((( SELECT auth.uid() AS uid) = ( SELECT quizzes.author_id
   FROM quizzes
  WHERE (quizzes.id = ( SELECT quizzes_questions.quiz
           FROM quizzes_questions
          WHERE (quizzes_questions.id = questions_hints.question_id))))) OR (( SELECT user_roles.user_role
   FROM user_roles
  WHERE (user_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types)));


create policy "user can update their data / admin can update all"
on "public"."questions_hints"
as permissive
for update
to authenticated
using (((( SELECT auth.uid() AS uid) = author_id) OR (( SELECT user_roles.user_role
   FROM user_roles
  WHERE (user_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types)));


create policy "user delete their data / admin delete all"
on "public"."questions_hints"
as permissive
for delete
to authenticated
using (((( SELECT auth.uid() AS uid) = author_id) OR (( SELECT user_roles.user_role
   FROM user_roles
  WHERE (user_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types)));



