create table "public"."mindamps" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text default ''::text,
    "image" text,
    "publishing_status" publishing_status,
    "author_id" uuid default gen_random_uuid()
);


alter table "public"."mindamps" enable row level security;

CREATE UNIQUE INDEX mindamps_pkey ON public.mindamps USING btree (id);

alter table "public"."mindamps" add constraint "mindamps_pkey" PRIMARY KEY using index "mindamps_pkey";

alter table "public"."mindamps" add constraint "mindamps_author_id_fkey" FOREIGN KEY (author_id) REFERENCES user_profiles(user_id) ON DELETE CASCADE not valid;

alter table "public"."mindamps" validate constraint "mindamps_author_id_fkey";

grant delete on table "public"."mindamps" to "anon";

grant insert on table "public"."mindamps" to "anon";

grant references on table "public"."mindamps" to "anon";

grant select on table "public"."mindamps" to "anon";

grant trigger on table "public"."mindamps" to "anon";

grant truncate on table "public"."mindamps" to "anon";

grant update on table "public"."mindamps" to "anon";

grant delete on table "public"."mindamps" to "authenticated";

grant insert on table "public"."mindamps" to "authenticated";

grant references on table "public"."mindamps" to "authenticated";

grant select on table "public"."mindamps" to "authenticated";

grant trigger on table "public"."mindamps" to "authenticated";

grant truncate on table "public"."mindamps" to "authenticated";

grant update on table "public"."mindamps" to "authenticated";

grant delete on table "public"."mindamps" to "service_role";

grant insert on table "public"."mindamps" to "service_role";

grant references on table "public"."mindamps" to "service_role";

grant select on table "public"."mindamps" to "service_role";

grant trigger on table "public"."mindamps" to "service_role";

grant truncate on table "public"."mindamps" to "service_role";

grant update on table "public"."mindamps" to "service_role";


