create type "public"."summarization_source" as enum ('youtube', 'pdf', 'image');

drop policy "Service role can do anything" on "public"."document_summarizations";

revoke delete on table "public"."document_summarizations" from "anon";

revoke insert on table "public"."document_summarizations" from "anon";

revoke references on table "public"."document_summarizations" from "anon";

revoke select on table "public"."document_summarizations" from "anon";

revoke trigger on table "public"."document_summarizations" from "anon";

revoke truncate on table "public"."document_summarizations" from "anon";

revoke update on table "public"."document_summarizations" from "anon";

revoke delete on table "public"."document_summarizations" from "authenticated";

revoke insert on table "public"."document_summarizations" from "authenticated";

revoke references on table "public"."document_summarizations" from "authenticated";

revoke select on table "public"."document_summarizations" from "authenticated";

revoke trigger on table "public"."document_summarizations" from "authenticated";

revoke truncate on table "public"."document_summarizations" from "authenticated";

revoke update on table "public"."document_summarizations" from "authenticated";

revoke delete on table "public"."document_summarizations" from "service_role";

revoke insert on table "public"."document_summarizations" from "service_role";

revoke references on table "public"."document_summarizations" from "service_role";

revoke select on table "public"."document_summarizations" from "service_role";

revoke trigger on table "public"."document_summarizations" from "service_role";

revoke truncate on table "public"."document_summarizations" from "service_role";

revoke update on table "public"."document_summarizations" from "service_role";

alter table "public"."document_summarizations" drop constraint "document_summarizations_user_id_fkey";

alter table "public"."document_summarizations" drop constraint "document_summarizations_pkey";

drop index if exists "public"."document_summarizations_pkey";

drop table "public"."document_summarizations";

create table "public"."summarizations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "content" jsonb,
    "source" summarization_source,
    "name" text
);


alter table "public"."summarizations" enable row level security;

create table "public"."summarizations_logs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "pages_count" bigint default '0'::bigint,
    "user_id" uuid default gen_random_uuid(),
    "is_refunded" boolean default false
);


alter table "public"."summarizations_logs" enable row level security;

CREATE INDEX questions_hints_author_id_idx ON public.questions_hints USING btree (author_id);

CREATE INDEX questions_hints_id_idx ON public.questions_hints USING btree (id);

CREATE UNIQUE INDEX summarizations_pkey ON public.summarizations USING btree (id);

CREATE UNIQUE INDEX document_summarizations_pkey ON public.summarizations_logs USING btree (id);

alter table "public"."summarizations" add constraint "summarizations_pkey" PRIMARY KEY using index "summarizations_pkey";

alter table "public"."summarizations_logs" add constraint "document_summarizations_pkey" PRIMARY KEY using index "document_summarizations_pkey";

alter table "public"."summarizations" add constraint "summarizations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profiles(user_id) ON DELETE CASCADE not valid;

alter table "public"."summarizations" validate constraint "summarizations_user_id_fkey";

alter table "public"."summarizations_logs" add constraint "document_summarizations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profiles(user_id) ON DELETE SET NULL not valid;

alter table "public"."summarizations_logs" validate constraint "document_summarizations_user_id_fkey";

grant delete on table "public"."summarizations" to "anon";

grant insert on table "public"."summarizations" to "anon";

grant references on table "public"."summarizations" to "anon";

grant select on table "public"."summarizations" to "anon";

grant trigger on table "public"."summarizations" to "anon";

grant truncate on table "public"."summarizations" to "anon";

grant update on table "public"."summarizations" to "anon";

grant delete on table "public"."summarizations" to "authenticated";

grant insert on table "public"."summarizations" to "authenticated";

grant references on table "public"."summarizations" to "authenticated";

grant select on table "public"."summarizations" to "authenticated";

grant trigger on table "public"."summarizations" to "authenticated";

grant truncate on table "public"."summarizations" to "authenticated";

grant update on table "public"."summarizations" to "authenticated";

grant delete on table "public"."summarizations" to "service_role";

grant insert on table "public"."summarizations" to "service_role";

grant references on table "public"."summarizations" to "service_role";

grant select on table "public"."summarizations" to "service_role";

grant trigger on table "public"."summarizations" to "service_role";

grant truncate on table "public"."summarizations" to "service_role";

grant update on table "public"."summarizations" to "service_role";

grant delete on table "public"."summarizations_logs" to "anon";

grant insert on table "public"."summarizations_logs" to "anon";

grant references on table "public"."summarizations_logs" to "anon";

grant select on table "public"."summarizations_logs" to "anon";

grant trigger on table "public"."summarizations_logs" to "anon";

grant truncate on table "public"."summarizations_logs" to "anon";

grant update on table "public"."summarizations_logs" to "anon";

grant delete on table "public"."summarizations_logs" to "authenticated";

grant insert on table "public"."summarizations_logs" to "authenticated";

grant references on table "public"."summarizations_logs" to "authenticated";

grant select on table "public"."summarizations_logs" to "authenticated";

grant trigger on table "public"."summarizations_logs" to "authenticated";

grant truncate on table "public"."summarizations_logs" to "authenticated";

grant update on table "public"."summarizations_logs" to "authenticated";

grant delete on table "public"."summarizations_logs" to "service_role";

grant insert on table "public"."summarizations_logs" to "service_role";

grant references on table "public"."summarizations_logs" to "service_role";

grant select on table "public"."summarizations_logs" to "service_role";

grant trigger on table "public"."summarizations_logs" to "service_role";

grant truncate on table "public"."summarizations_logs" to "service_role";

grant update on table "public"."summarizations_logs" to "service_role";

create policy "authenticated users can insert data"
on "public"."summarizations"
as permissive
for insert
to authenticated
with check (true);


create policy "service role can do anything"
on "public"."summarizations"
as permissive
for all
to service_role
using (true);


create policy "users can delete their data and admin all"
on "public"."summarizations"
as permissive
for delete
to authenticated
using (((( SELECT auth.uid() AS uid) = user_id) OR (( SELECT user_roles.user_role
   FROM user_roles
  WHERE (user_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types)));


create policy "users can select their data and admin all data"
on "public"."summarizations"
as permissive
for select
to authenticated
using (((( SELECT auth.uid() AS uid) = user_id) OR (( SELECT user_roles.user_role
   FROM user_roles
  WHERE (user_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types)));


create policy "users can update their data and admin all"
on "public"."summarizations"
as permissive
for update
to authenticated
using (((( SELECT auth.uid() AS uid) = user_id) OR (( SELECT user_roles.user_role
   FROM user_roles
  WHERE (user_roles.user_id = ( SELECT auth.uid() AS uid))) = 'ADMIN'::user_role_types)));


create policy "Service role can do anything"
on "public"."summarizations_logs"
as permissive
for all
to service_role
using (true);



