create table "public"."quiz_submission_answers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "quiz_submission" bigint,
    "question_id" bigint,
    "seconds_spent" bigint default '0'::bigint,
    "is_answered_correctly" boolean,
    "selected_content" jsonb default '[]'::jsonb
);


alter table "public"."quiz_submission_answers" enable row level security;

create table "public"."quiz_submissions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default gen_random_uuid(),
    "quiz_id" bigint,
    "seconds_spent" bigint default '0'::bigint
);


alter table "public"."quiz_submissions" enable row level security;

alter table "public"."quizzes" add column "author_id" uuid;

CREATE UNIQUE INDEX quiz_submission_answers_pkey ON public.quiz_submission_answers USING btree (id);

CREATE UNIQUE INDEX quiz_submissions_pkey ON public.quiz_submissions USING btree (id);

alter table "public"."quiz_submission_answers" add constraint "quiz_submission_answers_pkey" PRIMARY KEY using index "quiz_submission_answers_pkey";

alter table "public"."quiz_submissions" add constraint "quiz_submissions_pkey" PRIMARY KEY using index "quiz_submissions_pkey";

alter table "public"."quiz_submission_answers" add constraint "quiz_submission_answers_question_id_fkey" FOREIGN KEY (question_id) REFERENCES quizzes_questions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."quiz_submission_answers" validate constraint "quiz_submission_answers_question_id_fkey";

alter table "public"."quiz_submission_answers" add constraint "quiz_submission_answers_quiz_submission_fkey" FOREIGN KEY (quiz_submission) REFERENCES quiz_submissions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."quiz_submission_answers" validate constraint "quiz_submission_answers_quiz_submission_fkey";

alter table "public"."quiz_submissions" add constraint "quiz_submissions_quiz_id_fkey" FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."quiz_submissions" validate constraint "quiz_submissions_quiz_id_fkey";

alter table "public"."quiz_submissions" add constraint "quiz_submissions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."quiz_submissions" validate constraint "quiz_submissions_user_id_fkey";

alter table "public"."quizzes" add constraint "quizzes_author_id_fkey" FOREIGN KEY (author_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."quizzes" validate constraint "quizzes_author_id_fkey";

grant delete on table "public"."quiz_submission_answers" to "anon";

grant insert on table "public"."quiz_submission_answers" to "anon";

grant references on table "public"."quiz_submission_answers" to "anon";

grant select on table "public"."quiz_submission_answers" to "anon";

grant trigger on table "public"."quiz_submission_answers" to "anon";

grant truncate on table "public"."quiz_submission_answers" to "anon";

grant update on table "public"."quiz_submission_answers" to "anon";

grant delete on table "public"."quiz_submission_answers" to "authenticated";

grant insert on table "public"."quiz_submission_answers" to "authenticated";

grant references on table "public"."quiz_submission_answers" to "authenticated";

grant select on table "public"."quiz_submission_answers" to "authenticated";

grant trigger on table "public"."quiz_submission_answers" to "authenticated";

grant truncate on table "public"."quiz_submission_answers" to "authenticated";

grant update on table "public"."quiz_submission_answers" to "authenticated";

grant delete on table "public"."quiz_submission_answers" to "service_role";

grant insert on table "public"."quiz_submission_answers" to "service_role";

grant references on table "public"."quiz_submission_answers" to "service_role";

grant select on table "public"."quiz_submission_answers" to "service_role";

grant trigger on table "public"."quiz_submission_answers" to "service_role";

grant truncate on table "public"."quiz_submission_answers" to "service_role";

grant update on table "public"."quiz_submission_answers" to "service_role";

grant delete on table "public"."quiz_submissions" to "anon";

grant insert on table "public"."quiz_submissions" to "anon";

grant references on table "public"."quiz_submissions" to "anon";

grant select on table "public"."quiz_submissions" to "anon";

grant trigger on table "public"."quiz_submissions" to "anon";

grant truncate on table "public"."quiz_submissions" to "anon";

grant update on table "public"."quiz_submissions" to "anon";

grant delete on table "public"."quiz_submissions" to "authenticated";

grant insert on table "public"."quiz_submissions" to "authenticated";

grant references on table "public"."quiz_submissions" to "authenticated";

grant select on table "public"."quiz_submissions" to "authenticated";

grant trigger on table "public"."quiz_submissions" to "authenticated";

grant truncate on table "public"."quiz_submissions" to "authenticated";

grant update on table "public"."quiz_submissions" to "authenticated";

grant delete on table "public"."quiz_submissions" to "service_role";

grant insert on table "public"."quiz_submissions" to "service_role";

grant references on table "public"."quiz_submissions" to "service_role";

grant select on table "public"."quiz_submissions" to "service_role";

grant trigger on table "public"."quiz_submissions" to "service_role";

grant truncate on table "public"."quiz_submissions" to "service_role";

grant update on table "public"."quiz_submissions" to "service_role";


