drop policy "Service role can  do anything" on "public"."quizzes_refunds";

revoke delete on table "public"."quizzes_refunds" from "anon";

revoke insert on table "public"."quizzes_refunds" from "anon";

revoke references on table "public"."quizzes_refunds" from "anon";

revoke select on table "public"."quizzes_refunds" from "anon";

revoke trigger on table "public"."quizzes_refunds" from "anon";

revoke truncate on table "public"."quizzes_refunds" from "anon";

revoke update on table "public"."quizzes_refunds" from "anon";

revoke delete on table "public"."quizzes_refunds" from "authenticated";

revoke insert on table "public"."quizzes_refunds" from "authenticated";

revoke references on table "public"."quizzes_refunds" from "authenticated";

revoke select on table "public"."quizzes_refunds" from "authenticated";

revoke trigger on table "public"."quizzes_refunds" from "authenticated";

revoke truncate on table "public"."quizzes_refunds" from "authenticated";

revoke update on table "public"."quizzes_refunds" from "authenticated";

revoke delete on table "public"."quizzes_refunds" from "service_role";

revoke insert on table "public"."quizzes_refunds" from "service_role";

revoke references on table "public"."quizzes_refunds" from "service_role";

revoke select on table "public"."quizzes_refunds" from "service_role";

revoke trigger on table "public"."quizzes_refunds" from "service_role";

revoke truncate on table "public"."quizzes_refunds" from "service_role";

revoke update on table "public"."quizzes_refunds" from "service_role";

alter table "public"."quizzes_refunds" drop constraint "quizzes_refunds_quiz_id_fkey";

alter table "public"."quizzes_refunds" drop constraint "quizzes_refunds_user_id_fkey";

alter table "public"."quizzes_refunds" drop constraint "quizzes_refunds_pkey";

drop index if exists "public"."quizzes_refunds_pkey";

drop index if exists "public"."quizzes_refunds_quiz_id_idx";

drop table "public"."quizzes_refunds";

create table "public"."document_summarizations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "pages_count" bigint default '0'::bigint,
    "user_id" uuid default gen_random_uuid(),
    "is_refunded" boolean default false
);


alter table "public"."document_summarizations" enable row level security;

create table "public"."refunds" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "cause" text,
    "quiz_id" bigint,
    "user_id" uuid
);


alter table "public"."refunds" enable row level security;

CREATE UNIQUE INDEX document_summarizations_pkey ON public.document_summarizations USING btree (id);

CREATE UNIQUE INDEX quizzes_refunds_pkey ON public.refunds USING btree (id);

CREATE INDEX quizzes_refunds_quiz_id_idx ON public.refunds USING btree (quiz_id);

alter table "public"."document_summarizations" add constraint "document_summarizations_pkey" PRIMARY KEY using index "document_summarizations_pkey";

alter table "public"."refunds" add constraint "quizzes_refunds_pkey" PRIMARY KEY using index "quizzes_refunds_pkey";

alter table "public"."document_summarizations" add constraint "document_summarizations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profiles(user_id) ON DELETE SET NULL not valid;

alter table "public"."document_summarizations" validate constraint "document_summarizations_user_id_fkey";

alter table "public"."refunds" add constraint "quizzes_refunds_quiz_id_fkey" FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE SET NULL not valid;

alter table "public"."refunds" validate constraint "quizzes_refunds_quiz_id_fkey";

alter table "public"."refunds" add constraint "quizzes_refunds_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profiles(user_id) ON DELETE SET NULL not valid;

alter table "public"."refunds" validate constraint "quizzes_refunds_user_id_fkey";

grant delete on table "public"."document_summarizations" to "anon";

grant insert on table "public"."document_summarizations" to "anon";

grant references on table "public"."document_summarizations" to "anon";

grant select on table "public"."document_summarizations" to "anon";

grant trigger on table "public"."document_summarizations" to "anon";

grant truncate on table "public"."document_summarizations" to "anon";

grant update on table "public"."document_summarizations" to "anon";

grant delete on table "public"."document_summarizations" to "authenticated";

grant insert on table "public"."document_summarizations" to "authenticated";

grant references on table "public"."document_summarizations" to "authenticated";

grant select on table "public"."document_summarizations" to "authenticated";

grant trigger on table "public"."document_summarizations" to "authenticated";

grant truncate on table "public"."document_summarizations" to "authenticated";

grant update on table "public"."document_summarizations" to "authenticated";

grant delete on table "public"."document_summarizations" to "service_role";

grant insert on table "public"."document_summarizations" to "service_role";

grant references on table "public"."document_summarizations" to "service_role";

grant select on table "public"."document_summarizations" to "service_role";

grant trigger on table "public"."document_summarizations" to "service_role";

grant truncate on table "public"."document_summarizations" to "service_role";

grant update on table "public"."document_summarizations" to "service_role";

grant delete on table "public"."refunds" to "anon";

grant insert on table "public"."refunds" to "anon";

grant references on table "public"."refunds" to "anon";

grant select on table "public"."refunds" to "anon";

grant trigger on table "public"."refunds" to "anon";

grant truncate on table "public"."refunds" to "anon";

grant update on table "public"."refunds" to "anon";

grant delete on table "public"."refunds" to "authenticated";

grant insert on table "public"."refunds" to "authenticated";

grant references on table "public"."refunds" to "authenticated";

grant select on table "public"."refunds" to "authenticated";

grant trigger on table "public"."refunds" to "authenticated";

grant truncate on table "public"."refunds" to "authenticated";

grant update on table "public"."refunds" to "authenticated";

grant delete on table "public"."refunds" to "service_role";

grant insert on table "public"."refunds" to "service_role";

grant references on table "public"."refunds" to "service_role";

grant select on table "public"."refunds" to "service_role";

grant trigger on table "public"."refunds" to "service_role";

grant truncate on table "public"."refunds" to "service_role";

grant update on table "public"."refunds" to "service_role";

create policy "Service role can do anything"
on "public"."document_summarizations"
as permissive
for all
to service_role
using (true);


create policy "Service role can  do anything"
on "public"."refunds"
as permissive
for all
to service_role
using (true);



